site_name: Data Science
theme:
  name: material
  palette:
    primary: custom

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  
nav:
  - Home: index.md
  - FastAPI:
      - Einführung: fastapi/intro.md
      - Erste Schritte: fastapi/first_steps.md
      - Datenmodelle: fastapi/data_models.md
      - SQLModel: fastapi/sqlmodel.md
      - Aufgabe: fastapi/task.md
  - Data Analysis:
      - Einführung: data_analysis/intro.md
      - Datenvisualisierung: data_analysis/data_visualization.md
      - Datensätze verstehen: data_analysis/understand_datasets.md
      - EDA Schritte: data_analysis/eda_steps.md
      - Aufgaben: data_analysis/tasks.md
  - KW 49 und 50:
      - Überblick: KW49-50/overview.md
      - Data Cleaning: 
        - Einführung: KW49-50/data_processing/intro.md
        - Missing Values: KW49-50/data_processing/missing_values.md
        - Outliers: KW49-50/data_processing/outliers.md
        - Duplikate: KW49-50/data_processing/duplicates.md
        - Konvertierung: KW49-50/data_processing/type_conversion.md
      - Ziele: KW49-50/goals.md
  - KW 51:
      - Feature Engineering:
        - Encoding: KW51/feature_engineering/encoding.md
        - Scaling: KW51/feature_engineering/scaling.md
        - Transformation: KW51/feature_engineering/transformation.md
        - Feature Extraction: KW51/feature_engineering/feature_extraction.md
        - Erstellung neuer Features: KW51/feature_engineering/new_features.md
      # - Exkurs Klassifikation:
      #   - Einführung: KW51/excourse_classification/intro.md
      #   - Modelle trainieren: KW51/excourse_classification/train_models.md
      #   - Naive Bayes: KW51/excourse_classification/naive_bayes.md
      - Ziele: KW51/goals.md
  - KW 2:
      - Einführung statistisches und maschinelles Lernen: 
        - Modelle trainieren: KW2/statistical_and_machine_learning/train_models.md
        - Generalisierung: KW2/statistical_and_machine_learning/generalization.md
        - Test-Train Split: KW2/statistical_and_machine_learning/test_train_split.md
        - Exkurs Distanzmetriken: KW2/statistical_and_machine_learning/distance_metrics/distance_metrics.md
        - Exkurs Evaluation: KW2/statistical_and_machine_learning/evaluation.md
      - Entscheidungsbäume:
        - Einführung: KW2/decision_trees/intro.md
        - Split Kriterium: KW2/decision_trees/split-criteria.md
        - Exkurs Random Forest: KW2/decision_trees/random_forest.md
      - SVM:
        - SVM: KW2/svm/svm.md
      - Exkurs Naive Bayes:
        - Einführung: KW2/naive_bayes/intro.md
        - Naive Bayes: KW2/naive_bayes/naive_bayes.md
      - Exkurs K-Means: KW2/kmeans/k-means.md
      - Lineare Regression: KW2/linear_regression/linear_regression.md
      - Ziele: 
        - Einführung statistisches & maschinelles Lernen: KW2/goals.md
        - Dashboards: week5/goals.md
      - Aufgaben:
        - Car Features: KW2/assignments/car_features.md
  - KW 3:
      - Einführung Dashboards: KW3/intro.md
      - Streamlit:
        - Einführung: KW3/streamlit/intro.md
        - Struktur: KW3/streamlit/structure.md
        - Visualisierungen: KW3/streamlit/visualization.md
        - Layout: KW3/streamlit/layout.md
        - Umgang mit Daten: KW3/streamlit/data-handling.md
        - Interaktivität: KW3/streamlit/interactivity.md
        - Caching: KW3/streamlit/caching.md
        - Multipage Apps: KW3/streamlit/multipage-apps.md
        - Secrets und Authentication: KW3/streamlit/secrets-authentication.md
        - Ausblick: KW3/streamlit/outlook.md
      - Aufgaben:
        - Streamlit: KW3/assignments/streamlit.md
        - Dash: KW3/assignments/dash.md
  # - Woche 5:
  #     - Ziele: week5/goals.md
  - KW 4:
      - Ziele: KW4/goals.md
      - Skalierung: KW4/scaling.md
      - Metriken: KW4/metrics.md
      - Smote: KW4/smote.md
      - KNN: KW4/knn.md
      - PCA: KW4/pca.md
      - Cheat-Sheet: KW4/pca_smote_cheat_sheet.md
      - Aufgaben: 
        - Analytics Dashboard: KW4/assignments/analytics-dashbaord.md
        - Car Features - SMOTE und PCA: KW4/assignments/car-features.md
  - KW 5:
      - NLTK: 
        - Allgemein: KW5/nltk.md
        - Fachbegriffe: KW5/domain-specific-terms.md
        - Vader: KW5/vader.md
        - Weitere Methoden der Sentiment Analysis: KW5/extended_sentiment_analysis.md
        - Embeddings & Vektorisierung: KW5/vectorization_embeddings.md
        - Word2Vec & GloVe: KW5/word2vec_glove.md
      - Ziele: KW5/goals.md
      - Aufgaben: 
        - Gebrauchtwagen: KW5/assignments/used_cars.md
        - Shopping Reviews: KW5/assignments/shopping_reviews.md
  - KW 6:
      - Ziele: week8/goals.md
  - KW 7:
      - Ziele: week9/goals.md
  - Woche 10:
      - Ziele: KW49-500/goals.md
  - Woche 11:
      - Ziele: KW49-501/goals.md
      

# Weitere Einstellungen und Plugins können hier hinzugefügt werden.
